import = [
	"~/.config/alacritty/nord.toml",
]

[env]
TERM = "xterm-256color"

[window]
dimensions = { columns = 160, lines = 40 }
padding.x = 20
padding.y = 20
decorations = "None"
option_as_alt = "Both"
resize_increments = true

[font]
normal.family = "Iosevka Facile"

size = 12
