[buildPlans.iosevka-custom]
family = "Iosevka Custom"
spacing = "term"
serifs = "sans"
no-cv-ss = true
no-ligation = true

  [buildPlans.iosevka-custom.variants]
  inherits = "ss08"

    [buildPlans.iosevka-custom.variants.design]
    g = "double-storey-open"
    m = "short-leg"
    underscore = "high"
    paren = "normal"
    brace = "curly-flat-boundary"
    number-sign = "upright"
    ampersand = "et-toothless-rounded"
    at = "short"
    percent = "rings-segmented-slash"
