# Color scheme
BASE16_SHELL=$HOME/.config/base16-shell/
[ -n "$PS1" ] && [ -s $BASE16_SHELL/profile_helper.sh ] && eval "$($BASE16_SHELL/profile_helper.sh)"

# Prompt
export PS1="[\w]: "

# Aliases
alias cl='clear'
alias g='git'
# Mac
if [[ "$(uname -s)" == "Darwin" ]]; then
    alias showAll='defaults write com.apple.finder AppleShowAllFiles YES'
    alias hideAll='defaults write com.apple.finder AppleShowAllFiles NO'
fi

# Colors for ls
if ls --color=auto &> /dev/null; then
    alias ls="ls --color=auto"
else
    export CLICOLOR=1
fi

