# Brewfile to be used with `brew bundle`

# Taps
tap "homebrew/bundle"

# Formulae
brew "zsh"
brew "git"
brew "htop"
brew "tmux"
brew "ripgrep"
brew "vim"
brew "hugo"
brew "jq"
brew "shellcheck"
brew "fnm"
brew "neovim"

# Casks
cask "ghostty"
cask "emacs"
