# Brewfile to be used with `brew bundle`

# Taps
tap "homebrew/bundle"
tap "homebrew/core"

# Formulae
brew "zsh"
brew "git"
brew "htop"
brew "tmux"
brew "tree"
brew "ripgrep"
brew "vim"
brew "hugo"
brew "jq"
brew "shellcheck"
brew "fnm"
brew "fd"
brew "bat"
brew "rustup"

# Casks
cask "alacritty"
cask "emacs"
cask "visual-studio-code"
