# Brewfile to be used with `brew bundle`

# Taps
tap "homebrew/bundle"
tap "homebrew/core"

# Formulae
brew "zsh"
brew "git"
brew "htop"
brew "tmux"
brew "tree"
brew "the_silver_searcher"
brew "ripgrep"
brew "vim"
brew "hugo"
brew "jq"
brew "podman"
brew "shellcheck"
brew "fnm"

# Casks
cask "iterm2"
cask "emacs"
