[buildPlans.IosevkaFacile]
family = "Iosevka Facile"
spacing = "term"
serifs = "sans"
noCvSs = true
noLigation = true
exportGlyphNames = false

  [buildPlans.IosevkaFacile.variants]
  inherits = "ss08"

    [buildPlans.IosevkaFacile.variants.design]
    capital-a = "curly-serifless"
    capital-b = "more-asymmetric-serifless"
    capital-c = "serifless"
    capital-d = "more-rounded-serifless"
    capital-e = "serifless"
    capital-f = "serifless"
    capital-g = "toothless-rounded-serifless-hooked"
    capital-h = "serifless"
    capital-i = "serifed"
    capital-j = "serifless"
    capital-k = "curly-serifless"
    capital-l = "serifless"
    capital-m = "hanging-serifless"
    capital-n = "asymmetric-serifless"
    capital-p = "closed-serifless"
    capital-q = "straight"
    capital-r = "curly-serifless"
    capital-s = "serifless"
    capital-t = "serifless"
    capital-u = "toothless-rounded-serifless"
    capital-v = "curly-serifless"
    capital-w = "curly-serifless"
    capital-x = "curly-serifless"
    capital-y = "curly-serifless"
    capital-z = "curly-serifless-with-horizontal-crossbar"
    a = "double-storey-serifless"
    b = "toothed-serifless"
    c = "serifless"
    d = "toothed-serifless"
    e = "flat-crossbar"
    f = "flat-hook-serifless"
    g = "double-storey"
    h = "straight-serifless"
    i = "serifed"
    j = "serifed"
    k = "curly-serifless"
    l = "zshaped"
    m = "serifless"
    n = "straight-serifless"
    p = "eared-serifless"
    q = "straight-serifless"
    r = "serifless"
    s = "serifless"
    t = "flat-hook"
    u = "toothed-serifless"
    v = "curly-serifless"
    w = "curly-serifless"
    x = "curly-serifless"
    y = "curly-serifless"
    z = "curly-serifless"
    capital-eszet = "rounded-serifless"
    eszet = "sulzbacher-tailed-serifless"
    zero = "oval-reverse-slashed-split"
    one = "no-base"
    two = "curly-neck-serifless"
    three = "two-arcs"
    four = "closed-serifless"
    five = "upright-flat-serifless"
    six = "closed-contour"
    seven = "bend-serifless"
    eight = "two-circles"
    nine = "closed-contour"
    tittle = "round"
    diacritic-dot = "round"
    punctuation-dot = "round"
    braille-dot = "round"
    tilde = "low"
    asterisk = "penta-low"
    underscore = "high"
    caret = "medium"
    ascii-grave = "straight"
    ascii-single-quote = "straight"
    paren = "large-contour"
    brace = "straight"
    guillemet = "straight"
    number-sign = "slanted"
    ampersand = "upper-open"
    at = "threefold"
    dollar = "open"
    cent = "open"
    percent = "rings-continuous-slash"
    bar = "natural-slope"
    question = "smooth"
    micro-sign = "toothed-serifless"

  [buildPlans.IosevkaFacile.slopes]
  Upright = { angle = 0, shape = "upright", menu = "upright", css = "normal" }
  Italic = { angle = 9.4, shape = "italic", menu = "italic", css = "italic" }

  [buildPlans.IosevkaFacile.weights]
  Regular = { shape = 400, menu = 400, css = 400 }
  Bold = { shape = 700, menu = 700, css = 700 }

  [buildPlans.IosevkaFacile.widths]
  Normal = { shape = 500, menu = 5, css = "normal" }

