set encoding=utf-8

"
" Colors
" " " " "
set background=dark
colorscheme nord

"
" General
" " " " "
set number
set history=500
set autoread
set showcmd
set showmode
set nobackup
set nowritebackup
set noswapfile
set incsearch
set hlsearch

"
" Format
" " " " "
syntax on
set autoindent
set smartindent
set smarttab
set shiftwidth=4
set softtabstop=4
set tabstop=4
set expandtab
set list listchars=tab:\ \ ,nbsp:¬,extends:»,precedes:«,trail:·
set showbreak=↳\ 
set showmatch

"
" Statusline
" " " " "
set laststatus=2 " always show statusline
set showtabline=2 " always show tabline
set statusline=%#Search#\ %{SimpleMode()}\ %#StatusLineNC#\ %F\ %m%=%y\ %#Search#\ L%l\ C%c\ 

function! SimpleMode()
    let mode_cpy = mode()
    let m = get({"\x16": '^V', "\x13": '^S'}, mode_cpy, mode_cpy)
    return toupper(m)
endfunction
