set encoding=utf-8

"
" Colors
" " " " "
set background=dark
colorscheme nord

"
" General
" " " " "
set number
set history=500
set autoread
set showcmd
set showmode
set nobackup
set nowritebackup
set noswapfile
set incsearch
set hlsearch

"
" Format
" " " " "
syntax on
set autoindent
set smartindent
set smarttab
set shiftwidth=4
set softtabstop=4
set tabstop=4
set expandtab
set list listchars=tab:\ \ ,nbsp:¬,extends:»,precedes:«,trail:·
set showbreak=↳\ 
set showmatch

"
" Airline
" " " " "
set laststatus=2 " always show airline
let g:airline#extensions#tabline#enabled=1 " show tabline
let g:airline#extensions#tabline#fnamemod=':p'
let g:airline_section_z='%l:%c'
