#!/usr/bin/env bash

case "$1" in
    raise)
        amixer -D pulse set Master 5%+ unmute &>/dev/null
        ;;
    lower)
        amixer -D pulse set Master 5%- unmute &>/dev/null
        ;;
    mute)
        amixer -D pulse set Master toggle &>/dev/null
        ;;
esac

vol="$(amixer get Master | grep -o -E '[0-9]{1,3}%' | head -n 1)"

mute="$(amixer get Master | grep -o -E '\[[a-z]{2,3}\]' | grep -o -E '[a-z]{2,3}' | head -n 1)"

if [[ $mute == "off" ]]; then
    echo "Volume: $mute"
else
    echo "Volume: $vol"
fi
