[buildPlans.iosevka-term]
family = "Iosevka Term"
spacing = "term"
serifs = "sans"
no-cv-ss = true
no-ligation = true

  [buildPlans.iosevka-term.variants]
  inherits = "ss08"

    [buildPlans.iosevka-term.variants.design]
    capital-b = 'more-asymmetric-serifless'
    capital-j = 'serifed'
    capital-q = 'curly-tailed'
    capital-w = 'straight'
    g = "double-storey-open"
    i = 'serifed-flat-tailed'
    l = 'serifed-flat-tailed'
    m = "short-leg"
    t = 'flat-hook'
    w = 'straight'
    y = 'cursive'
    zero = 'long-dotted'
    four = 'semi-open'
    seven = 'straight-crossbar'
    underscore = "high"
    brace = "curly"
    number-sign = "upright"
    ampersand = "et-toothless-rounded"
    at = "short"
    percent = "rings-segmented-slash"
    question = 'corner'

  [buildPlans.iosevka-term.slopes]
  upright = { angle = 0, shape = "upright", menu = "upright", css = "normal" }
  italic = { angle = 9.4, shape = "italic", menu = "italic", css = "italic" }

  [buildPlans.iosevka-term.weights]
  medium = { shape = 500, menu = 500, css = 500 }
  bold = { shape = 700, menu = 700, css = 700 }

  [buildPlans.iosevka-term.widths]
  normal = { shape = 500, menu = 5, css = "normal" }
